name: swe437
on: [push]

jobs:
  build:
    name: swe437-assignment8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: TestingResearchIllinois/idoft
          ref: 3e2070733b75feed680553638c57b7e6ae253e1a      
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Test Project Repo
        run: git clone https://github.com/google/guava

      - run: cd guava
     
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: Huawei/vCenter_Plugin_DME
          ref: a197d99b96d69ea75a2c4a15ecd8a730dd3270d6
          
      - name: SWE_437 Compiling
        run: mvn test-compile -pl guava-test -am
        
      - name: SWE_437 Check Without NonDex
        run: mvn -pl guava-test test -Dtest=com.google.common.collect.FilteredCollectionsTest$SetsFilterHashSetTest#testForEach
        
      - name: SWE_437 Check With NonDex
        run: mvn -pl guava-test edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.google.common.collect.FilteredCollectionsTest$SetsFilterHashSetTest#testForEach -DnondexRuns=10  