name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    include:
      - remote :'https://github.com/Huawei/vCenter_Plugin_DME'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cloning test
        script:
          - mkdir test
          - cd test
          - clone dmestore-service
          - cd dmestore-service
      - name: SWE_437 Compiling
        shell: bash
        run: mvn test-compile -pl dmestore-service -am
      - name: SWE_437 Check Without NonDex
        shell: bash
        run:  mvn -pl dmestore-service test -Dtest=com.huawei.dmestore.services.DmeAccessServiceImplTest#testCreateHostGroup
      - name: SWE_437 Check With NonDex
        shell: bash
        run: mvn -pl -DnondexRuns=10 dmestore-service edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.huawei.dmestore.services.DmeAccessServiceImplTest#testCreateHostGroup
