name: swe437
on: [push]

jobs:
  build:
    name: swe437-assignment8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: TestingResearchIllinois/idoft
          ref: 3e2070733b75feed680553638c57b7e6ae253e1a      
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Test Project Repo
        run: git clone https://github.com/dropwizard/dropwizard

      - run: cd dropwizard

      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: dropwizard/dropwizard
          ref: df39fdeed1d14f7b014a22db59b06bfd4e562edd

      - name: SWE_437 Compiling
        run: mvn test-compile -pl dropwizard-health -am
        
      - name: SWE_437 Check Without NonDex
        run: mvn -pl dropwizard-health test -Dtest=io.dropwizard.health.response.JsonHealthResponseProviderTest#shouldHandleSingleHealthStateViewCorrectly
        
      - name: SWE_437 Check With NonDex
        run: mvn -pl dropwizard-health edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=io.dropwizard.health.response.JsonHealthResponseProviderTest#shouldHandleSingleHealthStateViewCorrectly -DnondexRuns=10