name: swe437
on: [push]

jobs:
  build:
    name: swe437-assignment8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: TestingResearchIllinois/idoft
          ref: 3e2070733b75feed680553638c57b7e6ae253e1a      
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Test Project Repo
        run: git clone https://github.com/Alluxio/alluxio
             
      - run: cd esper
     
      - name: Using Given Commit Verison
        uses: actions/checkout@v2
        with:
          repository: espertechinc/esper
          ref: 68fcda9dd2ca2181eb897e10ca02fa5bc3a3099f
          
      - name: SWE_437 Compiling
        run: mvn test-compile -pl core/server/worker -am
        
      - name: SWE_437 Check Without NonDex
        run: mvn -pl core/server/worker test -Dtest=org.springframework.data.r2dbc.core.R2dbcEntityTemplateUnitTests#shouldUpdateCorrectlyVersionedAndAudited -Drat.skip
        
      - name: SWE_437 Check With NonDex
        run: mvn -pl core/server/worker -DnondexRuns=10 dmestore-service edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.springframework.data.r2dbc.core.R2dbcEntityTemplateUnitTests#shouldUpdateCorrectlyVersionedAndAudited -DnondexRuns=10  