name: swe437
on: [push]

jobs:
  build:
    name: swe437-assignment8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: TestingResearchIllinois/idoft
          ref: 3e2070733b75feed680553638c57b7e6ae253e1a      
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Test Project Repo
        run: git clone https://github.com/wildfly/wildfly

      - run: cd wildfly
     
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: wildfly/wildfly
          ref: b19048b72669fc0e96665b1b125dc1fda21f5993

      - name: Maven Install for dependencies
        run: mvn install -DskipTests
          
      - name: SWE_437 Compiling
        run: mvn test-compile -pl dist -am
        
      - name: SWE_437 Check Without NonDex
        run: mvn -pl dist test -Dtest=org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneMinimalistic
        
      - name: SWE_437 Check With NonDex
        run: mvn -pl dist edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneMinimalistic -DnondexRuns=10  