name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make test directory
        shell: bash
        run: mkdir test
      - name: Going to test directory
        shell: bash
        run: cd test
      - name: Cloning test
        shell: bash
        run: git clone https://github.com/dropwizard/dropwizard
      - name: Going to Test Project
        shell: bash
        run: cd dropwizard
      - name: SWE_437 Compiling
        shell: bash
        run: mvn test-compile -pl dropwizard-health -am
      - name: SWE_437 Check Without NonDex
        shell: bash
        run:  mvn -pl dropwizard-health test -Dtest=io.dropwizard.health.response.JsonHealthResponseProviderTest#shouldHandleSingleHealthStateViewCorrectly
      - name: SWE_437 Check With NonDex
        shell: bash
        run: mvn -pl -DnondexRuns=10 dropwizard-health edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=io.dropwizard.health.response.JsonHealthResponseProviderTest#shouldHandleSingleHealthStateViewCorrectly
