name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make test directory
        shell: bash
        run: mkdir test
      - name: Going to test directory
        shell: bash
        run: cd test
      - name: Cloning test
        shell: bash
        run: git clone https://github.com/spring-projects/spring-data-r2dbc
      - name: Going to Test Project
        shell: bash
        run: cd spring-data-r2dbc
      - name: SWE_437 Compiling
        shell: bash
        run: mvn test-compile -pl spring-data-r2dbc -am -Drat.skip
      - name: SWE_437 Check Without NonDex
        shell: bash
        run:  mvn -pl spring-data-r2dbc test -Dtest=org.springframework.data.r2dbc.core.R2dbcEntityTemplateUnitTests#shouldUpdateCorrectlyVersionedAndAudited
      - name: SWE_437 Check With NonDex
        shell: bash
        run: mvn -pl -DnondexRuns=10 spring-data-r2dbc edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.springframework.data.r2dbc.core.R2dbcEntityTemplateUnitTests#shouldUpdateCorrectlyVersionedAndAudited
